CREATE DATABASE Czech_BANK;

USE Czech_BANK;

-- ----------------CREATING TABLES--------------
CREATE TABLE DISTRICT(
District_Code INT PRIMARY KEY	,
District_Name VARCHAR(100)	,
Region VARCHAR(100)	,
No_of_inhabitants	INT,
No_of_municipalities_with_inhabitants_less_499 INT,
No_of_municipalities_with_inhabitants_500_btw_1999	INT,
No_of_municipalities_with_inhabitants_2000_btw_9999	INT,
No_of_municipalities_with_inhabitants_less_10000 INT,	
No_of_cities	INT,
Ratio_of_urban_inhabitants	FLOAT,
Average_salary	INT,
No_of_entrepreneurs_per_1000_inhabitants INT,
No_committed_crime_2017	INT,
No_committed_crime_2018 INT
) ;



CREATE TABLE ACCOUNT(
account_id INT PRIMARY KEY,
district_id	INT,
frequency	VARCHAR(40),
Date DATE ,
FOREIGN KEY (district_id) references DISTRICT(District_Code) 
);

CREATE TABLE ORDER_LIST (
order_id	INT PRIMARY KEY,
account_id	INT,
bank_to	VARCHAR(45),
account_to	INT,
amount FLOAT,
FOREIGN KEY (account_id) references ACCOUNT(account_id)
);



CREATE TABLE LOAN(
loan_id	INT ,
account_id	INT,
Date	DATE,
amount	INT,
duration	INT,
payments	INT,
status VARCHAR(35),
FOREIGN KEY (account_id) references ACCOUNT(account_id)
);



CREATE TABLE TRANSACTIONS(
trans_id INT,	
account_id	INT,
Date	DATE,
Type	VARCHAR(30),
operation	VARCHAR(40),
amount	INT,
balance	FLOAT,
Purpose	VARCHAR(40),
bank	VARCHAR(45),
account_partner_id INT,
FOREIGN KEY (account_id) references ACCOUNT(account_id));


CREATE TABLE CLIENT(
client_id	INT PRIMARY KEY,
Sex	CHAR(10),
Birth_date	DATE,
district_id INT,
FOREIGN KEY (district_id) references DISTRICT(District_Code) 
);


CREATE TABLE DISPOSITION(
disp_id	INT PRIMARY KEY,
client_id INT,
account_id	INT,
type CHAR(15),
FOREIGN KEY (account_id) references ACCOUNT(account_id),
FOREIGN KEY (client_id) references CLIENT(client_id)
);


CREATE TABLE CARD(
card_id	INT PRIMARY KEY,
disp_id	INT,
type CHAR(10)	,
issued DATE,
FOREIGN KEY (disp_id) references DISPOSITION(disp_id)
);

---------------------------------------------------------------------------------------------
-- USE STAGE INTEGRATION TO IMPORT FILES FROM AWS TO SNOWFLAKE----------------------------
USE BANKING_DB;
USE BANKING_DB.BANKING_SCHEMA;

CREATE OR REPLACE STORAGE integration s3_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN ='arn:aws:iam::347301642642:role/CzeckBankRole'
STORAGE_ALLOWED_LOCATIONS =('s3://banking-buck/');

DESC integration s3_int;

-- CREATE FILE FORMAT
create or replace file format banking_csv
type = 'csv'
compression = 'none'
field_delimiter = ','
field_optionally_enclosed_by = 'none'
skip_header = 1;

-- CREATE STAGE
CREATE OR REPLACE STAGE BANKING_STAGE
URL ='s3://banking-buck'
file_format=banking_csv
storage_integration =s3_int;

SHOW STAGES;


--CREATE SNOWPIPE THAT RECOGNISES CSV THAT ARE INGESTED FROM EXTERNAL STAGE AND COPIES THE DATA INTO PATIENTS TABLE
--The AUTO_INGEST=true parameter specifies to read event notifications sent from an S3 bucket to an SQS queue when new data is ready to load.


USE BANKING_DB;
USE BANKING_DB.BANKING_SCHEMA;

-- CREATE PIPELINE FOR THE FLOW OF DATA FROM S3 BUCKET TO SNOWFLAKE TABLES

CREATE OR REPLACE PIPE DISTRICT_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.DISTRICT
FROM '@BANKING_STAGE/District/' 
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE ACCOUNT_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.ACCOUNT
FROM '@BANKING_STAGE/Account/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE TRANSACTIONS_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.TRANSACTIONS
FROM '@BANKING_STAGE/TRANSACTIONS/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE DISPOSITION_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.DISPOSITION
FROM '@BANKING_STAGE/Desposition/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE CARD_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.CARD
FROM '@BANKING_STAGE/Card/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE ORDER_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.ORDER_LIST
FROM '@BANKING_STAGE/ORDER_LIST/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE LOAN_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.LOAN
FROM '@BANKING_STAGE/Loan/'
FILE_FORMAT = banking_csv;

CREATE OR REPLACE PIPE CLIENT_PIPE AUTO_INGEST = TRUE AS
COPY INTO BANKING_DB.BANKING_SCHEMA.CLIENT
FROM '@BANKING_STAGE/Client/'
FILE_FORMAT = banking_csv;


SHOW PIPES;

--------------------------------------------------------
-- AUTOMATIC REFRESH 

ALTER PIPE ACCOUNT_PIPE refresh;

ALTER PIPE CARD_PIPE refresh;

ALTER PIPE TRANSACTIONS_PIPE refresh;

ALTER PIPE DISPOSITION_PIPE refresh;

ALTER PIPE ORDER_PIPE refresh;

ALTER PIPE LOAN_PIPE refresh;

ALTER PIPE CLIENT_PIPE refresh;

ALTER PIPE DISTRICT_PIPE refresh;

-----------------------------------------------

SELECT count(*) FROM DISTRICT;
SELECT count(*) FROM ACCOUNT;
SELECT count(*) FROM TRANSACTIONS;
SELECT count(*) FROM DISPOSITION;
SELECT count(*) FROM CARD;
SELECT count(*) FROM ORDER_LIST;
SELECT count(*) FROM LOAN;
SELECT count(*) FROM CLIENT;

------------------------------------------------
-- CREATED STORED PROCEDURES WHENEVER CLIENT DUMP DATA INTO S3 BUCKET THEN IT AUTOMATICALLY
-- UPDATE IN TABLE THROUH TASKS.

USE BANKING_DB;
----------------------------STORE PROCEDURE---------------------------------
SELECT * FROM BANKING_DB.BANKING_SCHEMA.TRANSACTIONS;

SELECT BANK, YEAR(DATE) AS TXN_YR,TYPE, COUNT(DISTINCT TRANS_ID) AS TOT_TXNS
FROM BANKING_DB.BANKING_SCHEMA.TRANSACTIONS
GROUP BY 1,2,3
ORDER BY 1,2,3 DESC;

CREATE OR REPLACE PROCEDURE CREAT_OR_REPLACE_ACC_LATEST()
RETURNS STRING
LANGUAGE SQL
AS
$$
  CREATE OR REPLACE TABLE ACC_LATEST_TXNS_WITH_BALANCE 
AS(
SELECT LTD.*,TXN.BALANCE
FROM BANKING_DB.BANKING_SCHEMA.TRANSACTIONS AS TXN
INNER JOIN 
(
   SELECT ACCOUNT_ID,YEAR(DATE) AS TXN_YEAR,
   MONTH(DATE) AS TXN_MONTH,
   MAX(DATE) AS LATEST_TXN_DATE
   FROM BANKING_DB.BANKING_SCHEMA.TRANSACTIONS
   GROUP BY 1,2,3
   ORDER BY 1,2,3

) AS LTD ON TXN.ACCOUNT_ID = LTD.ACCOUNT_ID AND TXN.DATE = LTD.LATEST_TXN_DATE
WHERE TXN.TYPE = 'Credit' -- this is the assumptions am having : month end txn data is credit
ORDER BY TXN.ACCOUNT_ID,LTD.TXN_YEAR,LTD.TXN_MONTH);
$$;

SHOW PROCEDURES;


CREATE OR REPLACE PROCEDURE CREATE_OR_REPLACE_BANKINGKPI()
RETURNS STRING
LANGUAGE SQL
AS
$$
  CREATE OR REPLACE TABLE BANKING_KPI AS(
SELECT  ALWB.TXN_YEAR , ALWB.TXN_MONTH,T.BANK,A.ACCOUNT_TYPE,

COUNT(DISTINCT ALWB.ACCOUNT_ID) AS TOT_ACCOUNT, 
COUNT(DISTINCT T.TRANS_ID) AS TOT_TXNS,
COUNT(CASE WHEN T.TYPE = 'Credit' THEN 1 END) AS DEPOSIT_COUNT ,
COUNT(CASE WHEN T.TYPE = 'Withdrawal' THEN 1 END) AS WITHDRAWAL_COUNT,

SUM(ALWB.BALANCE) AS TOT_BALANCE,

ROUND((DEPOSIT_COUNT / TOT_TXNS) * 100,2)  AS DEPOSIT_PERC ,
ROUND((WITHDRAWAL_COUNT / TOT_TXNS) * 100,2) AS WITHDRAWAL_PERC ,
NVL(TOT_BALANCE / TOT_ACCOUNT,0) AS AVG_BALANCE,

ROUND(TOT_TXNS/TOT_ACCOUNT,0) AS TPA

FROM BANKING_DB.BANKING_SCHEMA.TRANSACTIONS AS T
INNER JOIN  ACC_LATEST_TXNS_WITH_BALANCE AS ALWB ON T.ACCOUNT_ID = ALWB.ACCOUNT_ID
LEFT OUTER JOIN  BANKING_DB.BANKING_SCHEMA.ACCOUNT AS A ON T.ACCOUNT_ID = A.ACCOUNT_ID
GROUP BY 1,2,3,4
ORDER BY 1,2,3,4);
$$;  

CALL CREAT_OR_REPLACE_ACC_LATEST();
CALL CREATE_OR_REPLACE_BANKINGKPI();  
  
  

CREATE OR REPLACE TASK  ACC_LATEST_TXNS_WITH_BALANCE
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '1 MINUTE'          
AS CALL CREAT_OR_REPLACE_ACC_LATEST();
  
CREATE OR REPLACE TASK  BANKING_KPI
WAREHOUSE = COMPUTE_WH
SCHEDULE =  '2 MINUTE'
AS CALL CREATE_OR_REPLACE_BANKINGKPI();  
  
SHOW TASKS;  
  
ALTER TASK ACC_LATEST_TXNS_WITH_BALANCE  RESUME;
ALTER TASK ACC_LATEST_TXNS_WITH_BALANCE SUSPEND;  
ALTER TASK  BANKING_KPI RESUME;
ALTER TASK BANKING_KPI SUSPEND;    

  
DROP TASK IF EXISTS ACC_LATEST_TXNS_WITH_BALANCE;
DROP TASK IF EXISTS  BANKING_KPI; 
  
DROP TABLE  ACC_LATEST_TXNS_WITH_BALANCE;
DROP TABLE  BANKING_KPI;  
  
SELECT * FROM ACC_LATEST_TXNS_WITH_BALANCE;
SELECT * FROM BANKING_KPI;  

